version: '3'
services:
  jupyter:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/home/jovyan/
    ports:
      - "8888:8888"
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"        